##### Package installation script ------

install.packages("magrittr")
install.packages("read_xl")
install.packages("tidyverse")
install.packages("lubridate")
install.packages("types")
install.packages("pdftools")
install.packages("gt")
install.packages("scales")
install.packages("formattable")
install.packages("DT")
install.packages("janitor")
install.packages("kableExtra")
install.packages("tidygraph")
